### ISSUE TITLE
CSP Roadmap to NSR

### ISSUE THREAD

**Issue by richiksc** [TheGreenMachine/Zodiac#85]
- [ ] Increase turret ROM #86
- [ ] Drivetrain mounted driver camera - collector view
- [ ] Tuned shooter buckets at constant intervals #84
- [ ] Inches based aim biasing #89
- [ ] 5 ball opposing trench auto #60
- [ ] 8 ball auto (opposing and alliance side) #60
- [ ] Photosensor based ball loader sequencing #90 
- [ ] Mathematical shooter velocity calculation #91 
- [ ] Goal based turret tracking #92 
- [ ] Vision aiming while being defended without drift #83
- [ ] Algorithmic vision shape detection #87
- [ ] Continuous vision with latency and drivetrain compensation #93 
- [ ] 10 ball auto #60 
- [ ] 12 ball auto??? #60
- [ ] TCP socket based vision communication
